---
# This playbook deploys a simple standalone Tomcat 7 server.
- name: install from git with password
  hosts: monitor-server
  remote_user: '{{ user_name }}'
  become: yes

  roles:
    - git-clone
