--- 
###task.yml
- name: Get updated files from git repository 
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/test_hp_exporter.git
    dest: /tmp    
    version: master
